//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace JobPortal
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class JobPortalLogin : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new JobPortalLogin object using the connection string found in the 'JobPortalLogin' section of the application configuration file.
        /// </summary>
        public JobPortalLogin() : base("name=JobPortalLogin", "JobPortalLogin")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new JobPortalLogin object.
        /// </summary>
        public JobPortalLogin(string connectionString) : base(connectionString, "JobPortalLogin")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new JobPortalLogin object.
        /// </summary>
        public JobPortalLogin(EntityConnection connection) : base(connection, "JobPortalLogin")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<login> logins
        {
            get
            {
                if ((_logins == null))
                {
                    _logins = base.CreateObjectSet<login>("logins");
                }
                return _logins;
            }
        }
        private ObjectSet<login> _logins;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the logins EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTologins(login login)
        {
            base.AddObject("logins", login);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="JobPortalModel", Name="login")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class login : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new login object.
        /// </summary>
        /// <param name="loginid">Initial value of the loginid property.</param>
        /// <param name="useremail_fk">Initial value of the useremail_fk property.</param>
        /// <param name="userpassword">Initial value of the userpassword property.</param>
        public static login Createlogin(global::System.Int32 loginid, global::System.String useremail_fk, global::System.String userpassword)
        {
            login login = new login();
            login.loginid = loginid;
            login.useremail_fk = useremail_fk;
            login.userpassword = userpassword;
            return login;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 loginid
        {
            get
            {
                return _loginid;
            }
            set
            {
                if (_loginid != value)
                {
                    OnloginidChanging(value);
                    ReportPropertyChanging("loginid");
                    _loginid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("loginid");
                    OnloginidChanged();
                }
            }
        }
        private global::System.Int32 _loginid;
        partial void OnloginidChanging(global::System.Int32 value);
        partial void OnloginidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String useremail_fk
        {
            get
            {
                return _useremail_fk;
            }
            set
            {
                if (_useremail_fk != value)
                {
                    Onuseremail_fkChanging(value);
                    ReportPropertyChanging("useremail_fk");
                    _useremail_fk = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("useremail_fk");
                    Onuseremail_fkChanged();
                }
            }
        }
        private global::System.String _useremail_fk;
        partial void Onuseremail_fkChanging(global::System.String value);
        partial void Onuseremail_fkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String userpassword
        {
            get
            {
                return _userpassword;
            }
            set
            {
                if (_userpassword != value)
                {
                    OnuserpasswordChanging(value);
                    ReportPropertyChanging("userpassword");
                    _userpassword = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("userpassword");
                    OnuserpasswordChanged();
                }
            }
        }
        private global::System.String _userpassword;
        partial void OnuserpasswordChanging(global::System.String value);
        partial void OnuserpasswordChanged();

        #endregion

    
    }

    #endregion

    
}
